version: "3"
services: 
  master:
    build: ./master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MASTER_HOST=master
  worker-0:
    build: ./worker
    ports:
      - "8081:8080"
    environment:
      - SPARK_MASTER=spark://master:7077
  worker-1:
    build: ./worker
    ports:
      - "8082:8080"
    environment:
      - SPARK_MASTER=spark://master:7077
